In [1]:
import pandas as pd

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/25/dl9l232n2qlc1k4jjhh_zxdw0000gn/T/ipykernel_73392/4080736814.py", line 1, in <module>
    import pandas as pd
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas.compat import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/25/dl9l232n2qlc1k4jjhh_zxdw0000gn/T/ipykernel_73392/4080736814.py", line 1, in <module>
    import pandas as pd
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/25/dl9l232n2qlc1k4jjhh_zxdw0000gn/T/ipykernel_73392/4080736814.py", line 1, in <module>
    import pandas as pd
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/array.py", line 50, in <module>
    from pandas.core import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/25/dl9l232n2qlc1k4jjhh_zxdw0000gn/T/ipykernel_73392/4080736814.py", line 1, in <module>
    import pandas as pd
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py", line 60, in <module>
    from pandas.core import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

In [69]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [52]:
players = pd.read_csv('player_splits.csv')
goalies = pd.read_csv('goalie_splits.csv')

In [53]:
players.head()

,Player,id,link,Opponent,GP,G,A,PTS,GW
0,Mitch Marner,marnemi01,/players/g/granlmi01.html,Anaheim Ducks,15,2,13,15,0
1,Mitch Marner,marnemi01,/players/g/granlmi01.html,Arizona Coyotes,12,3,8,11,0
2,Mitch Marner,marnemi01,/players/g/granlmi01.html,Boston Bruins,28,13,33,46,3
3,Mitch Marner,marnemi01,/players/g/granlmi01.html,Buffalo Sabres,27,7,27,34,2
4,Mitch Marner,marnemi01,/players/g/granlmi01.html,Calgary Flames,23,8,10,18,3

In [54]:
players['Total_Goals'] = players.groupby('Player')['G'].transform('sum')
players['Total_Points'] = players.groupby('Player')['PTS'].transform('sum')
players['Total_GP'] = players.groupby('Player')['GP'].transform('sum')

In [55]:
players.head()

,Player,id,link,Opponent,GP,G,A,PTS,GW,Total_Goals,Total_Points,Total_GP
0,Mitch Marner,marnemi01,/players/g/granlmi01.html,Anaheim Ducks,15,2,13,15,0,212,715,636
1,Mitch Marner,marnemi01,/players/g/granlmi01.html,Arizona Coyotes,12,3,8,11,0,212,715,636
2,Mitch Marner,marnemi01,/players/g/granlmi01.html,Boston Bruins,28,13,33,46,3,212,715,636
3,Mitch Marner,marnemi01,/players/g/granlmi01.html,Buffalo Sabres,27,7,27,34,2,212,715,636
4,Mitch Marner,marnemi01,/players/g/granlmi01.html,Calgary Flames,23,8,10,18,3,212,715,636

In [56]:
players['Goals_Perc'] = players['G'] / players['Total_Goals']
players['Points_Perc'] = players['PTS'] / players['Total_Points']

In [60]:
#Data Cleaning

#Removing Players with less than 100 career games played
players = players[players['Total_GP'] >= 100]

#Removing rows where GP is less than 15
players = players[players['GP'] >= 15]

players.head()

,Player,id,link,Opponent,GP,G,A,PTS,GW,Total_Goals,Total_Points,Total_GP,Goals_Perc,Points_Perc
0,Mitch Marner,marnemi01,/players/g/granlmi01.html,Anaheim Ducks,15,2,13,15,0,212,715,636,0.009434,0.020979
2,Mitch Marner,marnemi01,/players/g/granlmi01.html,Boston Bruins,28,13,33,46,3,212,715,636,0.061321,0.064336
3,Mitch Marner,marnemi01,/players/g/granlmi01.html,Buffalo Sabres,27,7,27,34,2,212,715,636,0.033019,0.047552
4,Mitch Marner,marnemi01,/players/g/granlmi01.html,Calgary Flames,23,8,10,18,3,212,715,636,0.037736,0.025175
5,Mitch Marner,marnemi01,/players/g/granlmi01.html,Carolina Hurricanes,19,8,11,19,3,212,715,636,0.037736,0.026573

In [58]:
idx = players.groupby('Opponent')['Points_Perc'].idxmax()

top_points_perc = players.loc[idx, ['Opponent', 'Player', 'Points_Perc']].reset_index(drop=True)

top_points_perc.head(20)

                 Opponent              Player  Points_Perc
0           Anaheim Ducks         Tomáš Nosek     0.103448
1         Arizona Coyotes           Max Jones     0.129032
2           Boston Bruins      Rasmus Asplund     0.081633
3          Buffalo Sabres      Nathan Bastian     0.104478
4          Calgary Flames    Jesse Puljujärvi     0.110236
5     Carolina Hurricanes         Jimmy Vesey     0.088542
6      Chicago Blackhawks        Yakov Trenin     0.105263
7      Colorado Avalanche         Sean Walker     0.093458
8   Columbus Blue Jackets        Brock McGinn     0.094937
9            Dallas Stars       Connor Murphy     0.082803
10      Detroit Red Wings      Mathieu Joseph     0.096552
11        Edmonton Oilers      Nils Höglander     0.116505
12       Florida Panthers       Zach Bogosian     0.087866
13      Los Angeles Kings     Jordan Greenway     0.081761
14         Minnesota Wild     Zach Whitecloud     0.117647
15     Montreal Canadiens      Connor Clifton     0.130435
16    Nashville Predators     Luke Glendening     0.084337
17      New Jersey Devils       Chad Ruhwedel     0.120000
18     New York Islanders       Chad Ruhwedel     0.100000
19       New York Rangers  Nicolas Aubé-Kubel     0.112500

In [59]:
idx = players.groupby('Opponent')['Goals_Perc'].idxmax()

top_goals_perc = players.loc[idx, ['Opponent', 'Player', 'Goals_Perc']].reset_index(drop=True)

top_goals_perc.head(20)

                 Opponent                 Player  Goals_Perc
0           Anaheim Ducks       Kurtis MacDermid    0.181818
1         Arizona Coyotes              Max Jones    0.161290
2           Boston Bruins     Rasmus Ristolainen    0.107143
3          Buffalo Sabres          Ryan Lindgren    0.166667
4          Calgary Flames        Erik Brännström    0.200000
5     Carolina Hurricanes           Matt Benning    0.117647
6      Chicago Blackhawks           Troy Stecher    0.136364
7      Colorado Avalanche            Sean Walker    0.142857
8   Columbus Blue Jackets         Brian Dumoulin    0.153846
9            Dallas Stars    Trevor van Riemsdyk    0.125000
10      Detroit Red Wings         Scott Laughton    0.122642
11        Edmonton Oilers           Carson Soucy    0.120000
12       Florida Panthers      Marcus Pettersson    0.117647
13      Los Angeles Kings        Ilya Lyubushkin    0.200000
14         Minnesota Wild             Ben Hutton    0.166667
15     Montreal Canadiens         Connor Clifton    0.142857
16    Nashville Predators          Jani Hakanpää    0.200000
17      New Jersey Devils          Matt Grzelcyk    0.192308
18     New York Islanders  Pierre-Olivier Joseph    0.250000
19       New York Rangers     Nicolas Aubé-Kubel    0.125000

In [61]:
idx = players.groupby('Opponent')['G'].idxmax()

top_goals_perc = players.loc[idx, ['Opponent', 'Player', 'G']].reset_index(drop=True)

top_goals_perc.head(20)

                 Opponent          Player   G
0           Anaheim Ducks    Anže Kopitar  31
1         Arizona Coyotes     Corey Perry  29
2           Boston Bruins   Alex Ovechkin  29
3          Buffalo Sabres   Alex Ovechkin  41
4          Calgary Flames  Connor McDavid  29
5     Carolina Hurricanes   Alex Ovechkin  51
6      Chicago Blackhawks    Matt Duchene  22
7      Colorado Avalanche    Tyler Seguin  26
8   Columbus Blue Jackets    Patrick Kane  28
9            Dallas Stars    Patrick Kane  32
10      Detroit Red Wings   Alex Ovechkin  25
11        Edmonton Oilers     Corey Perry  27
12       Florida Panthers   Alex Ovechkin  45
13      Los Angeles Kings     Corey Perry  25
14         Minnesota Wild    Patrick Kane  25
15     Montreal Canadiens   Alex Ovechkin  39
16    Nashville Predators  Leon Draisaitl  27
17      New Jersey Devils   Alex Ovechkin  42
18     New York Islanders   Alex Ovechkin  44
19       New York Rangers   Alex Ovechkin  45

In [62]:
idx = players.groupby('Opponent')['PTS'].idxmax()

top_points_perc = players.loc[idx, ['Opponent', 'Player', 'PTS']].reset_index(drop=True)

top_points_perc.head(20)

                 Opponent            Player  PTS
0           Anaheim Ducks      Anže Kopitar   88
1         Arizona Coyotes      Anže Kopitar   95
2           Boston Bruins     Sidney Crosby   75
3          Buffalo Sabres     Sidney Crosby   85
4          Calgary Flames      Anže Kopitar   61
5     Carolina Hurricanes     Alex Ovechkin  105
6      Chicago Blackhawks        Jamie Benn   54
7      Colorado Avalanche      Anže Kopitar   63
8   Columbus Blue Jackets      Patrick Kane   86
9            Dallas Stars      Patrick Kane   76
10      Detroit Red Wings      Patrick Kane   56
11        Edmonton Oilers      Patrick Kane   69
12       Florida Panthers     Alex Ovechkin   90
13      Los Angeles Kings       Brent Burns   55
14         Minnesota Wild  Nathan MacKinnon   63
15     Montreal Canadiens     Alex Ovechkin   70
16    Nashville Predators      Patrick Kane   71
17      New Jersey Devils     Sidney Crosby   93
18     New York Islanders     Sidney Crosby  136
19       New York Rangers     Sidney Crosby  109

In [63]:
Avalanche = players[players['Opponent'] == 'Colorado Avalanche']
Rangers = players[players['Opponent'] == 'New York Rangers']

In [70]:
Avalanche.sort_values("G", ascending = False).head(10)
Avalanche.sort_values("PTS", ascending = False).head(10)
Avalanche.sort_values("Goals_Perc", ascending = False).head(10)
Avalanche.sort_values("Points_Perc", ascending = False).head(10)

,Player,id,link,Opponent,GP,G,A,PTS,GW,Total_Goals,Total_Points,Total_GP,Goals_Perc,Points_Perc
14004,Tyler Seguin,seguity01,/players/g/granlmi01.html,Colorado Avalanche,42,26,23,49,1,360,808,988,0.072222,0.060644
3499,David Perron,perroda01,/players/g/granlmi01.html,Colorado Avalanche,53,22,22,44,3,312,773,1153,0.070513,0.056921
2400,Patrick Kane,NaN,/players/g/granlmi01.html,Colorado Avalanche,60,21,34,55,4,486,1322,1280,0.043210,0.041604
23979,Jordan Eberle,eberljo01,/players/g/granlmi01.html,Colorado Avalanche,44,20,18,38,1,305,714,1039,0.065574,0.053221
20214,Corey Perry,perryco01,/players/g/granlmi01.html,Colorado Avalanche,59,20,22,42,7,442,926,1370,0.045249,0.045356
17575,Filip Forsberg,forsbfi01,/players/g/granlmi01.html,Colorado Avalanche,39,19,20,39,5,309,659,758,0.061489,0.059181
20620,Anže Kopitar,kopitan01,/players/g/granlmi01.html,Colorado Avalanche,65,18,45,63,1,433,1259,1432,0.041570,0.050040
7430,Brent Burns,burnsbr01,/players/g/granlmi01.html,Colorado Avalanche,76,18,34,52,1,259,902,1476,0.069498,0.057650
7674,Taylor Hall,NaN,/players/g/granlmi01.html,Colorado Avalanche,34,17,22,39,2,276,723,889,0.061594,0.053942
16161,Brayden Schenn,schenbr01,/players/g/granlmi01.html,Colorado Avalanche,42,16,12,28,3,272,673,1002,0.058824,0.041605

,Player,id,link,Opponent,GP,G,A,PTS,GW,Total_Goals,Total_Points,Total_GP,Goals_Perc,Points_Perc
20620,Anže Kopitar,kopitan01,/players/g/granlmi01.html,Colorado Avalanche,65,18,45,63,1,433,1259,1432,0.041570,0.050040
2400,Patrick Kane,NaN,/players/g/granlmi01.html,Colorado Avalanche,60,21,34,55,4,486,1322,1280,0.043210,0.041604
7430,Brent Burns,burnsbr01,/players/g/granlmi01.html,Colorado Avalanche,76,18,34,52,1,259,902,1476,0.069498,0.057650
14004,Tyler Seguin,seguity01,/players/g/granlmi01.html,Colorado Avalanche,42,26,23,49,1,360,808,988,0.072222,0.060644
13716,Jamie Benn,NaN,/players/g/granlmi01.html,Colorado Avalanche,60,15,34,49,1,398,945,1172,0.037688,0.051852
17640,Roman Josi,NaN,/players/g/granlmi01.html,Colorado Avalanche,47,15,30,45,4,190,724,962,0.078947,0.062155
3499,David Perron,perroda01,/players/g/granlmi01.html,Colorado Avalanche,53,22,22,44,3,312,773,1153,0.070513,0.056921
20214,Corey Perry,perryco01,/players/g/granlmi01.html,Colorado Avalanche,59,20,22,42,7,442,926,1370,0.045249,0.045356
16453,Ryan Suter,suterry01,/players/g/granlmi01.html,Colorado Avalanche,86,5,37,42,0,106,693,1506,0.047170,0.060606
12865,Mark Scheifele,scheima01,/players/g/granlmi01.html,Colorado Avalanche,39,13,27,40,0,331,784,858,0.039275,0.051020

,Player,id,link,Opponent,GP,G,A,PTS,GW,Total_Goals,Total_Points,Total_GP,Goals_Perc,Points_Perc
7495,Sean Walker,walkese01,/players/g/granlmi01.html,Colorado Avalanche,20,4,6,10,0,28,107,374,0.142857,0.093458
12897,Gabriel Vilardi,vilarga01,/players/g/granlmi01.html,Colorado Avalanche,21,10,2,12,1,89,169,260,0.112360,0.071006
20247,Brett Kulak,kulakbr01,/players/g/granlmi01.html,Colorado Avalanche,17,3,3,6,1,28,121,558,0.107143,0.049587
17802,Colton Sissons,sissoco01,/players/g/granlmi01.html,Colorado Avalanche,30,10,10,20,2,95,219,677,0.105263,0.091324
2709,Ben Chiarot,chiarbe01,/players/g/granlmi01.html,Colorado Avalanche,27,4,3,7,0,44,166,701,0.090909,0.042169
5121,Hampus Lindholm,lindhha01,/players/g/granlmi01.html,Colorado Avalanche,27,6,6,12,1,73,313,762,0.082192,0.038339
17640,Roman Josi,NaN,/players/g/granlmi01.html,Colorado Avalanche,47,15,30,45,4,190,724,962,0.078947,0.062155
16194,Colton Parayko,parayco01,/players/g/granlmi01.html,Colorado Avalanche,39,6,9,15,2,76,293,720,0.078947,0.051195
14972,Devin Shore,shorede01,/players/g/granlmi01.html,Colorado Avalanche,21,4,7,11,0,52,143,481,0.076923,0.076923
5962,Jordan Greenway,greenjo02,/players/g/granlmi01.html,Colorado Avalanche,20,4,4,8,0,55,159,426,0.072727,0.050314

,Player,id,link,Opponent,GP,G,A,PTS,GW,Total_Goals,Total_Points,Total_GP,Goals_Perc,Points_Perc
7495,Sean Walker,walkese01,/players/g/granlmi01.html,Colorado Avalanche,20,4,6,10,0,28,107,374,0.142857,0.093458
17802,Colton Sissons,sissoco01,/players/g/granlmi01.html,Colorado Avalanche,30,10,10,20,2,95,219,677,0.105263,0.091324
14972,Devin Shore,shorede01,/players/g/granlmi01.html,Colorado Avalanche,21,4,7,11,0,52,143,481,0.076923,0.076923
17198,Lawson Crouse,crousla01,/players/g/granlmi01.html,Colorado Avalanche,31,7,9,16,0,112,210,564,0.062500,0.076190
19754,Ben Hutton,huttobe01,/players/g/granlmi01.html,Colorado Avalanche,23,0,9,9,0,24,122,514,0.000000,0.073770
14165,Mathew Dumba,dumbama01,/players/g/granlmi01.html,Colorado Avalanche,42,3,15,18,1,83,253,715,0.036145,0.071146
12897,Gabriel Vilardi,vilarga01,/players/g/granlmi01.html,Colorado Avalanche,21,10,2,12,1,89,169,260,0.112360,0.071006
24874,Matt Benning,bennima01,/players/g/granlmi01.html,Colorado Avalanche,18,0,7,7,0,17,102,464,0.000000,0.068627
2918,Austin Watson,watsoau01,/players/g/granlmi01.html,Colorado Avalanche,20,4,4,8,0,60,118,517,0.066667,0.067797
9041,Kevin Labanc,labanke01,/players/g/granlmi01.html,Colorado Avalanche,24,4,11,15,1,84,237,512,0.047619,0.063291

In [71]:
Rangers.sort_values("G", ascending = False).head(10)
Rangers.sort_values("PTS", ascending = False).head(10)
Rangers.sort_values("Goals_Perc", ascending = False).head(10)
Rangers.sort_values("Points_Perc", ascending = False).head(10)

,Player,id,link,Opponent,GP,G,A,PTS,GW,Total_Goals,Total_Points,Total_GP,Goals_Perc,Points_Perc
6343,Alex Ovechkin,ovechal01,/players/g/granlmi01.html,New York Rangers,75,45,26,71,8,884,1598,1471,0.050905,0.044431
11959,Sidney Crosby,crosbsi01,/players/g/granlmi01.html,New York Rangers,88,40,69,109,7,611,1661,1333,0.065466,0.065623
12089,Evgeni Malkin,malkiev01,/players/g/granlmi01.html,New York Rangers,77,32,40,72,10,510,1337,1198,0.062745,0.053852
20193,Jeff Skinner,skinnje01,/players/g/granlmi01.html,New York Rangers,53,19,12,31,1,368,691,1059,0.051630,0.044863
11136,Brock Nelson,nelsobr01,/players/g/granlmi01.html,New York Rangers,51,19,18,37,3,294,572,900,0.064626,0.064685
17717,Steven Stamkos,stamkst01,/players/g/granlmi01.html,New York Rangers,44,19,24,43,2,572,1170,1142,0.033217,0.036752
4586,David Pastrňák,pastrda01,/players/g/granlmi01.html,New York Rangers,37,18,22,40,2,380,802,736,0.047368,0.049875
114,John Tavares,tavarjo01,/players/g/granlmi01.html,New York Rangers,59,16,34,50,1,480,1092,1163,0.033333,0.045788
7787,Jack Hughes,hugheja03,/players/g/granlmi01.html,New York Rangers,23,16,12,28,1,141,351,368,0.113475,0.079772
3153,Claude Giroux,giroucl01,/players/g/granlmi01.html,New York Rangers,73,16,48,64,2,362,1105,1242,0.044199,0.057919

,Player,id,link,Opponent,GP,G,A,PTS,GW,Total_Goals,Total_Points,Total_GP,Goals_Perc,Points_Perc
11959,Sidney Crosby,crosbsi01,/players/g/granlmi01.html,New York Rangers,88,40,69,109,7,611,1661,1333,0.065466,0.065623
12089,Evgeni Malkin,malkiev01,/players/g/granlmi01.html,New York Rangers,77,32,40,72,10,510,1337,1198,0.062745,0.053852
6343,Alex Ovechkin,ovechal01,/players/g/granlmi01.html,New York Rangers,75,45,26,71,8,884,1598,1471,0.050905,0.044431
3153,Claude Giroux,giroucl01,/players/g/granlmi01.html,New York Rangers,73,16,48,64,2,362,1105,1242,0.044199,0.057919
114,John Tavares,tavarjo01,/players/g/granlmi01.html,New York Rangers,59,16,34,50,1,480,1092,1163,0.033333,0.045788
12187,Kris Letang,letankr01,/players/g/granlmi01.html,New York Rangers,70,12,34,46,4,174,766,1143,0.068966,0.060052
4618,Brad Marchand,marchbr03,/players/g/granlmi01.html,New York Rangers,51,11,33,44,1,422,976,1090,0.026066,0.045082
17717,Steven Stamkos,stamkst01,/players/g/granlmi01.html,New York Rangers,44,19,24,43,2,572,1170,1142,0.033217,0.036752
6439,John Carlson,carlsjo01,/players/g/granlmi01.html,New York Rangers,54,7,33,40,0,155,713,1070,0.045161,0.056101
4586,David Pastrňák,pastrda01,/players/g/granlmi01.html,New York Rangers,37,18,22,40,2,380,802,736,0.047368,0.049875

,Player,id,link,Opponent,GP,G,A,PTS,GW,Total_Goals,Total_Points,Total_GP,Goals_Perc,Points_Perc
6168,Nicolas Aubé-Kubel,aubekni01,/players/g/granlmi01.html,New York Rangers,21,4,5,9,0,32,80,301,0.125000,0.112500
7787,Jack Hughes,hugheja03,/players/g/granlmi01.html,New York Rangers,23,16,12,28,1,141,351,368,0.113475,0.079772
6570,Nic Dowd,NaN,/players/g/granlmi01.html,New York Rangers,28,9,3,12,2,81,170,561,0.111111,0.070588
12219,Anthony Beauvillier,beauvan01,/players/g/granlmi01.html,New York Rangers,34,13,13,26,2,129,266,612,0.100775,0.097744
22366,Teddy Blueger,bluegte01,/players/g/granlmi01.html,New York Rangers,16,4,3,7,0,46,143,396,0.086957,0.048951
15017,Jonathon Merrill,merrijo01,/players/g/granlmi01.html,New York Rangers,18,2,1,3,0,23,113,662,0.086957,0.026549
4781,Charlie McAvoy,mcavoch01,/players/g/granlmi01.html,New York Rangers,27,5,9,14,0,60,300,504,0.083333,0.046667
10653,Garnet Hathaway,hathaga01,/players/g/granlmi01.html,New York Rangers,25,6,4,10,1,73,157,599,0.082192,0.063694
9020,Sean Kuraly,kuralse01,/players/g/granlmi01.html,New York Rangers,29,5,2,7,0,63,149,540,0.079365,0.046980
23156,Brian Dumoulin,dumoubr01,/players/g/granlmi01.html,New York Rangers,35,2,9,11,0,26,170,685,0.076923,0.064706

,Player,id,link,Opponent,GP,G,A,PTS,GW,Total_Goals,Total_Points,Total_GP,Goals_Perc,Points_Perc
6168,Nicolas Aubé-Kubel,aubekni01,/players/g/granlmi01.html,New York Rangers,21,4,5,9,0,32,80,301,0.125000,0.112500
12219,Anthony Beauvillier,beauvan01,/players/g/granlmi01.html,New York Rangers,34,13,13,26,2,129,266,612,0.100775,0.097744
7787,Jack Hughes,hugheja03,/players/g/granlmi01.html,New York Rangers,23,16,12,28,1,141,351,368,0.113475,0.079772
11327,Mathew Barzal,barzama01,/players/g/granlmi01.html,New York Rangers,31,10,25,35,1,134,462,530,0.074627,0.075758
6570,Nic Dowd,NaN,/players/g/granlmi01.html,New York Rangers,28,9,3,12,2,81,170,561,0.111111,0.070588
15398,Casey Mittelstadt,mitteca01,/players/g/granlmi01.html,New York Rangers,18,5,11,16,0,76,229,418,0.065789,0.069869
21529,Yegor Sharangovich,sharaye01,/players/g/granlmi01.html,New York Rangers,19,7,6,13,2,95,187,339,0.073684,0.069519
10492,Travis Sanheim,sanhetr01,/players/g/granlmi01.html,New York Rangers,30,2,12,14,0,52,210,558,0.038462,0.066667
12252,Marcus Pettersson,pettema01,/players/g/granlmi01.html,New York Rangers,23,1,9,10,0,17,152,500,0.058824,0.065789
11959,Sidney Crosby,crosbsi01,/players/g/granlmi01.html,New York Rangers,88,40,69,109,7,611,1661,1333,0.065466,0.065623

In [76]:
goalies['Total_SA'] = goalies.groupby('Player')['SA'].transform('sum')
goalies['Total_SV'] = goalies.groupby('Player')['SV'].transform('sum')
goalies['Career_SV%'] = goalies['Total_SV'] / goalies['Total_SA']
goalies['Total_GP'] = goalies.groupby('Player')['GP'].transform('sum')

In [78]:
#Data Cleaning

#Removing Goalies with less than 50 career games played
goalies = goalies[goalies['Total_GP'] >= 50]

#Removing rows where GP is less than 15
goalies = goalies[goalies['GP'] >= 5]

goalies.head(20)

,Player,id,link,Opponent,GP,W,L,T/O,GA,SA,SV,SV%,GAA,Total_SA,Total_SV,Career_SV%,Total_GP
1,Anthony Stolarz,stolaan01,/players/g/granlmi01.html,Arizona Coyotes,5,3,1,0,9,135,126,0.933,1.94,3572,3274,0.916573,130
4,Anthony Stolarz,stolaan01,/players/g/granlmi01.html,Calgary Flames,6,2,2,1,16,181,165,0.912,2.92,3572,3274,0.916573,130
6,Anthony Stolarz,stolaan01,/players/g/granlmi01.html,Chicago Blackhawks,5,2,2,0,13,122,109,0.893,2.82,3572,3274,0.916573,130
12,Anthony Stolarz,stolaan01,/players/g/granlmi01.html,Los Angeles Kings,6,1,3,1,13,169,156,0.923,2.41,3572,3274,0.916573,130
13,Anthony Stolarz,stolaan01,/players/g/granlmi01.html,Minnesota Wild,5,1,3,1,15,154,139,0.903,3.58,3572,3274,0.916573,130
14,Anthony Stolarz,stolaan01,/players/g/granlmi01.html,Montreal Canadiens,5,3,2,0,14,155,141,0.910,2.78,3572,3274,0.916573,130
16,Anthony Stolarz,stolaan01,/players/g/granlmi01.html,New Jersey Devils,7,2,1,1,13,201,188,0.935,2.13,3572,3274,0.916573,130
17,Anthony Stolarz,stolaan01,/players/g/granlmi01.html,New York Islanders,5,1,3,0,15,107,92,0.860,3.51,3572,3274,0.916573,130
18,Anthony Stolarz,stolaan01,/players/g/granlmi01.html,New York Rangers,6,2,3,0,12,172,160,0.930,2.30,3572,3274,0.916573,130
19,Anthony Stolarz,stolaan01,/players/g/granlmi01.html,Ottawa Senators,5,2,3,0,12,158,146,0.924,2.44,3572,3274,0.916573,130
22,Anthony Stolarz,stolaan01,/players/g/granlmi01.html,San Jose Sharks,14,10,1,1,32,438,406,0.927,2.42,3572,3274,0.916573,130
24,Anthony Stolarz,stolaan01,/players/g/granlmi01.html,St. Louis Blues,7,4,1,0,14,186,172,0.925,2.31,3572,3274,0.916573,130
26,Anthony Stolarz,stolaan01,/players/g/granlmi01.html,Toronto Maple Leafs,6,1,1,1,10,159,149,0.937,2.11,3572,3274,0.916573,130
31,Matt Murray,murrama02,/players/g/granlmi01.html,Anaheim Ducks,5,3,2,0,12,124,112,0.903,2.76,8074,7349,0.910206,274
32,Matt Murray,murrama02,/players/g/granlmi01.html,Arizona Coyotes,6,4,2,0,17,159,142,0.893,2.83,8074,7349,0.910206,274
33,Matt Murray,murrama02,/players/g/granlmi01.html,Boston Bruins,11,5,5,0,29,362,333,0.920,2.99,8074,7349,0.910206,274
34,Matt Murray,murrama02,/players/g/granlmi01.html,Buffalo Sabres,11,7,2,1,30,336,306,0.911,2.89,8074,7349,0.910206,274
35,Matt Murray,murrama02,/players/g/granlmi01.html,Calgary Flames,11,7,3,1,30,311,281,0.904,3.05,8074,7349,0.910206,274
36,Matt Murray,murrama02,/players/g/granlmi01.html,Carolina Hurricanes,14,7,4,2,27,443,416,0.939,1.96,8074,7349,0.910206,274
38,Matt Murray,murrama02,/players/g/granlmi01.html,Colorado Avalanche,5,4,1,0,11,151,140,0.927,2.16,8074,7349,0.910206,274

In [79]:
idx = goalies.groupby('Opponent')['SV%'].idxmax()

top_save_perc = goalies.loc[idx, ['Opponent', 'Player', 'SV%']].reset_index(drop=True)

top_save_perc.head(20)

                 Opponent              Player    SV%
0           Anaheim Ducks     Jonas Johansson  0.941
1         Arizona Coyotes        Ilya Sorokin  0.950
2           Boston Bruins      Anton Forsberg  0.935
3          Buffalo Sabres    Philipp Grubauer  0.944
4          Calgary Flames    Filip Gustavsson  0.953
5     Carolina Hurricanes      Calvin Pickard  0.964
6      Chicago Blackhawks      Thatcher Demko  0.955
7      Colorado Avalanche         Matt Murray  0.927
8   Columbus Blue Jackets       Vítek Vaněček  0.950
9            Dallas Stars         Matt Murray  0.948
10      Detroit Red Wings     Igor Shesterkin  0.943
11        Edmonton Oilers          Cam Talbot  0.934
12       Florida Panthers    Sergei Bobrovsky  0.940
13      Los Angeles Kings      Stuart Skinner  0.941
14         Minnesota Wild      Logan Thompson  0.950
15     Montreal Canadiens        Ilya Sorokin  0.949
16    Nashville Predators         Matt Murray  0.945
17      New Jersey Devils     Scott Wedgewood  0.965
18     New York Islanders  Andrei Vasilevskiy  0.936
19       New York Rangers         Juuse Saros  0.940

In [80]:
Avalanche_G = goalies[goalies['Opponent'] == 'Colorado Avalanche']
Rangers_G = goalies[goalies['Opponent'] == 'New York Rangers']

In [81]:
Avalanche_G.sort_values("SV%", ascending = False).head(10)

,Player,id,link,Opponent,GP,W,L,T/O,GA,SA,SV,SV%,GAA,Total_SA,Total_SV,Career_SV%,Total_GP
38,Matt Murray,murrama02,/players/g/granlmi01.html,Colorado Avalanche,5,4,1,0,11,151,140,0.927,2.16,8074,7349,0.910206,274
1834,Petr Mrázek,mrazepe01,/players/g/granlmi01.html,Colorado Avalanche,14,7,4,2,32,432,400,0.926,2.34,11936,10812,0.905831,423
2283,John Gibson,gibsojo02,/players/g/granlmi01.html,Colorado Avalanche,25,10,11,2,59,768,709,0.923,2.49,15314,13935,0.909952,502
1802,Juuse Saros,sarosju01,/players/g/granlmi01.html,Colorado Avalanche,13,7,3,2,32,414,382,0.923,2.53,11835,10829,0.914998,395
1153,Ilya Sorokin,sorokil01,/players/g/granlmi01.html,Colorado Avalanche,6,2,2,2,17,218,201,0.922,2.93,7104,6508,0.916104,237
1030,Igor Shesterkin,shestig01,/players/g/granlmi01.html,Colorado Avalanche,6,3,1,2,16,206,190,0.922,2.54,7623,7001,0.918405,257
609,James Reimer,reimeja01,/players/g/granlmi01.html,Colorado Avalanche,12,6,2,1,25,310,285,0.919,2.40,15035,13681,0.909943,514
1317,Connor Hellebuyck,helleco01,/players/g/granlmi01.html,Colorado Avalanche,27,16,7,4,72,882,810,0.918,2.69,16664,15291,0.917607,551
1209,Semyon Varlamov,varlasi01,/players/g/granlmi01.html,Colorado Avalanche,5,2,2,0,13,159,146,0.918,3.13,18625,17053,0.915597,621
1897,Ilya Samsonov,samsoil01,/players/g/granlmi01.html,Colorado Avalanche,5,3,1,1,11,132,121,0.917,2.25,5225,4711,0.901627,195

In [82]:
Rangers_G.sort_values("SV%", ascending = False).head(10)

,Player,id,link,Opponent,GP,W,L,T/O,GA,SA,SV,SV%,GAA,Total_SA,Total_SV,Career_SV%,Total_GP
1813,Juuse Saros,sarosju01,/players/g/granlmi01.html,New York Rangers,11,5,4,1,19,316,297,0.940,1.76,11835,10829,0.914998,395
18,Anthony Stolarz,stolaan01,/players/g/granlmi01.html,New York Rangers,6,2,3,0,12,172,160,0.930,2.30,3572,3274,0.916573,130
717,Pyotr Kochetkov,kochepy01,/players/g/granlmi01.html,New York Rangers,5,3,2,0,10,140,130,0.929,2.02,2645,2399,0.906994,106
534,Jeremy Swayman,swaymje01,/players/g/granlmi01.html,New York Rangers,8,3,3,2,16,226,210,0.929,2.00,4872,4449,0.913177,176
566,Ukko-Pekka Luukkonen,luukkuk01,/players/g/granlmi01.html,New York Rangers,8,3,3,2,17,238,221,0.929,2.13,4113,3706,0.901045,143
844,Jacob Markström,marksja02,/players/g/granlmi01.html,New York Rangers,19,11,4,3,41,522,481,0.921,2.24,14802,13457,0.909134,522
2390,Philipp Grubauer,grubaph01,/players/g/granlmi01.html,New York Rangers,14,5,7,1,31,368,337,0.916,2.46,9647,8759,0.907951,365
977,Elvis Merzļikins,merzlel01,/players/g/granlmi01.html,New York Rangers,9,2,6,1,26,311,285,0.916,3.03,6973,6296,0.902911,231
1221,Semyon Varlamov,varlasi01,/players/g/granlmi01.html,New York Rangers,24,14,8,2,62,729,667,0.915,2.59,18625,17053,0.915597,621
1942,Adin Hill,NaN,/players/g/granlmi01.html,New York Rangers,7,2,5,0,19,221,202,0.914,2.72,4614,4193,0.908756,172

In [86]:
players2 = pd.read_csv('player_splits.csv')
mcdavid = players2[players2['Player'] == 'Connor McDavid']
mcdavid

,Player,id,link,Opponent,GP,G,A,PTS,GW
19914,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Anaheim Ducks,30,15,38,53,4
19915,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Arizona Coyotes,26,18,20,38,4
19916,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Boston Bruins,15,6,16,22,0
19917,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Buffalo Sabres,15,6,12,18,3
19918,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Calgary Flames,42,29,29,58,10
19919,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Carolina Hurricanes,15,5,16,21,0
19920,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Chicago Blackhawks,23,11,21,32,4
19921,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Colorado Avalanche,24,14,21,35,2
19922,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Columbus Blue Jackets,18,9,25,34,1
19923,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Dallas Stars,22,11,19,30,0
19924,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Detroit Red Wings,17,5,21,26,1
19925,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Florida Panthers,15,8,19,27,1
19926,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Los Angeles Kings,34,17,27,44,3
19927,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Minnesota Wild,25,12,20,32,3
19928,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Montreal Canadiens,26,9,23,32,3
19929,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Nashville Predators,24,13,30,43,3
19930,Connor McDavid,mcdavco01,/players/g/granlmi01.html,New Jersey Devils,15,7,20,27,0
19931,Connor McDavid,mcdavco01,/players/g/granlmi01.html,New York Islanders,16,6,15,21,2
19932,Connor McDavid,mcdavco01,/players/g/granlmi01.html,New York Rangers,14,8,14,22,2
19933,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Ottawa Senators,26,13,33,46,3
19934,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Philadelphia Flyers,17,11,22,33,2
19935,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Pittsburgh Penguins,16,9,21,30,1
19936,Connor McDavid,mcdavco01,/players/g/granlmi01.html,San Jose Sharks,31,17,28,45,2
19937,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Seattle Kraken,13,8,11,19,0
19938,Connor McDavid,mcdavco01,/players/g/granlmi01.html,St. Louis Blues,26,10,20,30,2
19939,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Tampa Bay Lightning,14,12,8,20,3
19940,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Toronto Maple Leafs,25,12,25,37,1
19941,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Utah Hockey Club,2,1,3,4,0
19942,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Vancouver Canucks,42,24,44,68,7
19943,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Vegas Golden Knights,23,10,19,29,1
19944,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Washington Capitals,15,9,16,25,1
19945,Connor McDavid,mcdavco01,/players/g/granlmi01.html,Winnipeg Jets,33,12,44,56,3

In [88]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from IPython.display import HTML

fig, ax = plt.subplots()
line, = ax.plot([], [], lw=2)
text_box = ax.text(0.5, 1.05, '', transform=ax.transAxes, ha='center', fontsize=12, bbox=dict(facecolor='white', alpha=0.5))

# Set axis labels
ax.set_xlabel('Games Played')
ax.set_ylabel('Goals Scored')

# Set axis limits (adjust if needed)
ax.set_xlim(0, mcdavid['GP'].max() + 5)
ax.set_ylim(0, mcdavid['G'].max() + 2)

# Initialization function
def init():
    line.set_data([], [])
    text_box.set_text('')
    return line, text_box

# Animation function
def animate(i):
    row = mcdavid.iloc[i]
    x = [0, row['GP']]
    y = [0, row['G']]
    line.set_data(x, y)
    text_box.set_text(f"Opponent: {row['Opponent']}")
    return line, text_box

# Create animation
ani = animation.FuncAnimation(fig, animate, init_func=init,
                              frames=len(mcdavid), interval=1000, blit=True)

plt.close(fig)
# ani.save('/content/drive/MyDrive/velo.gif', writer='pillow')
HTML(ani.to_jshtml())

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/25/dl9l232n2qlc1k4jjhh_zxdw0000gn/T/ipykernel_73392/113484549.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (

AttributeError: _ARRAY_API not found

ImportError: numpy.core.multiarray failed to import