In [1]:
from urllib import request
from bs4 import BeautifulSoup
import pandas as pd

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/25/dl9l232n2qlc1k4jjhh_zxdw0000gn/T/ipykernel_33619/3428948516.py", line 3, in <module>
    import pandas as pd
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas.compat import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/25/dl9l232n2qlc1k4jjhh_zxdw0000gn/T/ipykernel_33619/3428948516.py", line 3, in <module>
    import pandas as pd
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/25/dl9l232n2qlc1k4jjhh_zxdw0000gn/T/ipykernel_33619/3428948516.py", line 3, in <module>
    import pandas as pd
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/array.py", line 50, in <module>
    from pandas.core import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/25/dl9l232n2qlc1k4jjhh_zxdw0000gn/T/ipykernel_33619/3428948516.py", line 3, in <module>
    import pandas as pd
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/arrow/array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py", line 60, in <module>
    from pandas.core import (
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/davidgold/opt/anaconda3/lib/python3.9/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
url = "https://www.basketball-reference.com/leagues/NBA_2025_per_game.html"

In [4]:
response = request.urlopen(url)
html = response.read().decode('utf8')

In [5]:
htmlsoup = BeautifulSoup(html, 'html.parser')

In [6]:
df_list = pd.read_html(str(htmlsoup))
player_stats = df_list[0]
player_stats = player_stats[player_stats['Player'] != 'Player'].reset_index(drop=True)
print(player_stats.head())

    Rk                   Player   Age Team Pos     G    GS    MP    FG   FGA  \
0  1.0  Shai Gilgeous-Alexander  26.0  OKC  PG  76.0  76.0  34.2  11.3  21.8
1  2.0    Giannis Antetokounmpo  30.0  MIL  PF  67.0  67.0  34.2  11.8  19.7
2  3.0             Nikola Jokić  29.0  DEN   C  70.0  70.0  36.7  11.2  19.5
3  4.0              Luka Dončić  25.0  2TM  PG  50.0  50.0  35.4   9.2  20.5
4  4.0              Luka Dončić  25.0  DAL  PG  22.0  22.0  35.7   9.8  21.2

   ...  ORB  DRB   TRB   AST  STL  BLK  TOV   PF   PTS  Awards
0  ...  0.9  4.1   5.0   6.4  1.7  1.0  2.4  2.2  32.7     NaN
1  ...  2.2  9.7  11.9   6.5  0.9  1.2  3.1  2.3  30.4     NaN
2  ...  2.9  9.9  12.7  10.2  1.8  0.6  3.3  2.3  29.6     NaN
3  ...  0.8  7.4   8.2   7.7  1.8  0.4  3.6  2.5  28.2     NaN
4  ...  0.7  7.6   8.3   7.8  2.0  0.4  3.4  2.6  28.1     NaN

[5 rows x 31 columns]

/var/folders/25/dl9l232n2qlc1k4jjhh_zxdw0000gn/T/ipykernel_33619/3861040375.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_list = pd.read_html(str(htmlsoup))

In [7]:
standingsurl = "https://www.basketball-reference.com/leagues/NBA_2025_standings.html"

In [8]:
response = request.urlopen(standingsurl)
html = response.read().decode('utf8')

In [9]:
htmlsoup = BeautifulSoup(html, 'html.parser')

In [10]:
df_list = pd.read_html(str(htmlsoup))
east_standings = df_list[0]
west_standings = df_list[1]
east_standings.head()

/var/folders/25/dl9l232n2qlc1k4jjhh_zxdw0000gn/T/ipykernel_33619/1878924706.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_list = pd.read_html(str(htmlsoup))

         Eastern Conference   W   L   W/L%    GB   PS/G   PA/G   SRS
0  Cleveland Cavaliers* (1)  64  18  0.780     —  121.9  112.4  8.81
1       Boston Celtics* (2)  61  21  0.744   3.0  116.3  107.2  8.28
2      New York Knicks* (3)  51  31  0.622  13.0  115.8  111.7  3.59
3       Indiana Pacers* (4)  50  32  0.610  14.0  117.4  115.1  1.68
4      Milwaukee Bucks* (5)  48  34  0.585  16.0  115.5  113.0  2.12

In [11]:
west_standings.head()

           Western Conference   W   L   W/L%    GB   PS/G   PA/G    SRS
0  Oklahoma City Thunder* (1)  68  14  0.829     —  120.5  107.6  12.70
1        Houston Rockets* (2)  52  30  0.634  16.0  114.3  109.8   4.97
2     Los Angeles Lakers* (3)  50  32  0.610  18.0  113.4  112.2   1.45
3         Denver Nuggets* (4)  50  32  0.610  18.0  120.8  116.9   3.97
4   Los Angeles Clippers* (5)  50  32  0.610  18.0  112.9  108.2   4.84

In [12]:
east_abbreviations = ['CLE', 'BOS', 'NYK', 'IND', 'MIL', 'DET', 'ORL', 'ATL', 'CHI', 'MIA', 'TOR', 'BKN', 'PHI', 'CHO', 'WAS']

east_standings['abbreviation'] = east_abbreviations

east_standings.head()

,Eastern Conference,W,L,W/L%,GB,PS/G,PA/G,SRS,abbreviation
0,Cleveland Cavaliers* (1),64,18,0.780,—,121.9,112.4,8.81,CLE
1,Boston Celtics* (2),61,21,0.744,3.0,116.3,107.2,8.28,BOS
2,New York Knicks* (3),51,31,0.622,13.0,115.8,111.7,3.59,NYK
3,Indiana Pacers* (4),50,32,0.610,14.0,117.4,115.1,1.68,IND
4,Milwaukee Bucks* (5),48,34,0.585,16.0,115.5,113.0,2.12,MIL

In [13]:
west_abbreviations = ['OKC', 'HOU', 'LAL', 'DEN', 'LAC', 'MIN', 'GSW', 'MEM', 'SAC', 'DAL', 'PHO', 'POR', 'SAS', 'NOP', 'UTA']

west_standings['abbreviation'] = west_abbreviations

west_standings.head()

,Western Conference,W,L,W/L%,GB,PS/G,PA/G,SRS,abbreviation
0,Oklahoma City Thunder* (1),68,14,0.829,—,120.5,107.6,12.70,OKC
1,Houston Rockets* (2),52,30,0.634,16.0,114.3,109.8,4.97,HOU
2,Los Angeles Lakers* (3),50,32,0.610,18.0,113.4,112.2,1.45,LAL
3,Denver Nuggets* (4),50,32,0.610,18.0,120.8,116.9,3.97,DEN
4,Los Angeles Clippers* (5),50,32,0.610,18.0,112.9,108.2,4.84,LAC

In [14]:
east_standings = east_standings.rename(columns={"Eastern Conference": "Team"})
west_standings = west_standings.rename(columns={"Western Conference": "Team"})

In [15]:
full_standings = pd.concat([east_standings, west_standings], ignore_index=True)

full_standings.head(20)

,Team,W,L,W/L%,GB,PS/G,PA/G,SRS,abbreviation
0,Cleveland Cavaliers* (1),64,18,0.780,—,121.9,112.4,8.81,CLE
1,Boston Celtics* (2),61,21,0.744,3.0,116.3,107.2,8.28,BOS
2,New York Knicks* (3),51,31,0.622,13.0,115.8,111.7,3.59,NYK
3,Indiana Pacers* (4),50,32,0.610,14.0,117.4,115.1,1.68,IND
4,Milwaukee Bucks* (5),48,34,0.585,16.0,115.5,113.0,2.12,MIL
5,Detroit Pistons* (6),44,38,0.537,20.0,115.5,113.6,1.73,DET
6,Orlando Magic* (7),41,41,0.500,23.0,105.4,105.5,-0.70,ORL
7,Atlanta Hawks* (8),40,42,0.488,24.0,118.2,119.3,-1.41,ATL
8,Chicago Bulls* (9),39,43,0.476,25.0,117.8,119.4,-1.83,CHI
9,Miami Heat* (10),37,45,0.451,27.0,110.6,110.0,0.11,MIA
10,Toronto Raptors (11),30,52,0.366,34.0,110.9,115.2,-4.40,TOR
11,Brooklyn Nets (12),26,56,0.317,38.0,105.1,112.2,-6.95,BKN
12,Philadelphia 76ers (13),24,58,0.293,40.0,109.6,115.8,-6.29,PHI
13,Charlotte Hornets (14),19,63,0.232,45.0,105.1,114.2,-9.10,CHO
14,Washington Wizards (15),18,64,0.220,46.0,108.0,120.4,-12.14,WAS
15,Oklahoma City Thunder* (1),68,14,0.829,—,120.5,107.6,12.70,OKC
16,Houston Rockets* (2),52,30,0.634,16.0,114.3,109.8,4.97,HOU
17,Los Angeles Lakers* (3),50,32,0.610,18.0,113.4,112.2,1.45,LAL
18,Denver Nuggets* (4),50,32,0.610,18.0,120.8,116.9,3.97,DEN
19,Los Angeles Clippers* (5),50,32,0.610,18.0,112.9,108.2,4.84,LAC

In [16]:
player_stats = player_stats.rename(columns={"Team": "abbreviation"})

In [17]:
full_df = player_stats.merge(full_standings, on='abbreviation', how='left')
full_df.head(10)

,Rk,Player,Age,abbreviation,Pos,G,GS,MP,FG,FGA,...,PTS,Awards,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,1.0,Shai Gilgeous-Alexander,26.0,OKC,PG,76.0,76.0,34.2,11.3,21.8,...,32.7,NaN,Oklahoma City Thunder* (1),68.0,14.0,0.829,—,120.5,107.6,12.70
1,2.0,Giannis Antetokounmpo,30.0,MIL,PF,67.0,67.0,34.2,11.8,19.7,...,30.4,NaN,Milwaukee Bucks* (5),48.0,34.0,0.585,16.0,115.5,113.0,2.12
2,3.0,Nikola Jokić,29.0,DEN,C,70.0,70.0,36.7,11.2,19.5,...,29.6,NaN,Denver Nuggets* (4),50.0,32.0,0.610,18.0,120.8,116.9,3.97
3,4.0,Luka Dončić,25.0,2TM,PG,50.0,50.0,35.4,9.2,20.5,...,28.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,Luka Dončić,25.0,DAL,PG,22.0,22.0,35.7,9.8,21.2,...,28.1,NaN,Dallas Mavericks* (10),39.0,43.0,0.476,29.0,114.2,115.4,-0.74
5,4.0,Luka Dončić,25.0,LAL,PG,28.0,28.0,35.1,8.8,20.0,...,28.2,NaN,Los Angeles Lakers* (3),50.0,32.0,0.610,18.0,113.4,112.2,1.45
6,5.0,Anthony Edwards,23.0,MIN,SG,79.0,79.0,36.3,9.1,20.4,...,27.6,NaN,Minnesota Timberwolves* (6),49.0,33.0,0.598,19.0,114.3,109.3,5.15
7,6.0,Jayson Tatum,26.0,BOS,PF,72.0,72.0,36.4,9.2,20.3,...,26.8,NaN,Boston Celtics* (2),61.0,21.0,0.744,3.0,116.3,107.2,8.28
8,7.0,Kevin Durant,36.0,PHO,PF,62.0,62.0,36.5,9.5,18.1,...,26.6,NaN,Phoenix Suns (11),36.0,46.0,0.439,32.0,113.6,116.6,-2.55
9,8.0,Tyrese Maxey,24.0,PHI,PG,52.0,52.0,37.7,9.2,21.0,...,26.3,NaN,Philadelphia 76ers (13),24.0,58.0,0.293,40.0,109.6,115.8,-6.29

In [18]:
#Data Cleaning

#Removing Players with less than 10 minutes played per game
full_df = full_df[full_df['MP'] > 10]

#Remvoing "2TM" Players by removing NAs in the Team column
full_df = full_df.dropna(subset=['Team'])
full_df.head(10)

full_df.to_csv('Full_NBA_Stats.csv', index=False)

,Rk,Player,Age,abbreviation,Pos,G,GS,MP,FG,FGA,...,PTS,Awards,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,1.0,Shai Gilgeous-Alexander,26.0,OKC,PG,76.0,76.0,34.2,11.3,21.8,...,32.7,NaN,Oklahoma City Thunder* (1),68.0,14.0,0.829,—,120.5,107.6,12.70
1,2.0,Giannis Antetokounmpo,30.0,MIL,PF,67.0,67.0,34.2,11.8,19.7,...,30.4,NaN,Milwaukee Bucks* (5),48.0,34.0,0.585,16.0,115.5,113.0,2.12
2,3.0,Nikola Jokić,29.0,DEN,C,70.0,70.0,36.7,11.2,19.5,...,29.6,NaN,Denver Nuggets* (4),50.0,32.0,0.610,18.0,120.8,116.9,3.97
4,4.0,Luka Dončić,25.0,DAL,PG,22.0,22.0,35.7,9.8,21.2,...,28.1,NaN,Dallas Mavericks* (10),39.0,43.0,0.476,29.0,114.2,115.4,-0.74
5,4.0,Luka Dončić,25.0,LAL,PG,28.0,28.0,35.1,8.8,20.0,...,28.2,NaN,Los Angeles Lakers* (3),50.0,32.0,0.610,18.0,113.4,112.2,1.45
6,5.0,Anthony Edwards,23.0,MIN,SG,79.0,79.0,36.3,9.1,20.4,...,27.6,NaN,Minnesota Timberwolves* (6),49.0,33.0,0.598,19.0,114.3,109.3,5.15
7,6.0,Jayson Tatum,26.0,BOS,PF,72.0,72.0,36.4,9.2,20.3,...,26.8,NaN,Boston Celtics* (2),61.0,21.0,0.744,3.0,116.3,107.2,8.28
8,7.0,Kevin Durant,36.0,PHO,PF,62.0,62.0,36.5,9.5,18.1,...,26.6,NaN,Phoenix Suns (11),36.0,46.0,0.439,32.0,113.6,116.6,-2.55
9,8.0,Tyrese Maxey,24.0,PHI,PG,52.0,52.0,37.7,9.2,21.0,...,26.3,NaN,Philadelphia 76ers (13),24.0,58.0,0.293,40.0,109.6,115.8,-6.29
10,9.0,Cade Cunningham,23.0,DET,PG,70.0,70.0,35.0,9.8,20.8,...,26.1,NaN,Detroit Pistons* (6),44.0,38.0,0.537,20.0,115.5,113.6,1.73

In [19]:
#League Leaders in Points, Assists, Rebounds, Field Goal %
full_df.nlargest(10, 'PTS')[['Player', 'Team', 'PTS']]
full_df.nlargest(10, 'TRB')[['Player', 'Team', 'TRB']]
full_df.nlargest(10, 'AST')[['Player', 'Team', 'AST']]
full_df.nlargest(10, 'FG%')[['Player', 'Team', 'FG%']]

                     Player                         Team   PTS
0   Shai Gilgeous-Alexander   Oklahoma City Thunder* (1)  32.7
1     Giannis Antetokounmpo         Milwaukee Bucks* (5)  30.4
2              Nikola Jokić          Denver Nuggets* (4)  29.6
5               Luka Dončić      Los Angeles Lakers* (3)  28.2
4               Luka Dončić       Dallas Mavericks* (10)  28.1
6           Anthony Edwards  Minnesota Timberwolves* (6)  27.6
7              Jayson Tatum          Boston Celtics* (2)  26.8
8              Kevin Durant            Phoenix Suns (11)  26.6
9              Tyrese Maxey      Philadelphia 76ers (13)  26.3
10          Cade Cunningham         Detroit Pistons* (6)  26.1

                    Player                         Team   TRB
62        Domantas Sabonis        Sacramento Kings* (9)  13.9
23      Karl-Anthony Towns         New York Knicks* (3)  12.8
2             Nikola Jokić          Denver Nuggets* (4)  12.7
94             Ivica Zubac    Los Angeles Clippers* (5)  12.6
184         Walker Kessler               Utah Jazz (15)  12.2
1    Giannis Antetokounmpo         Milwaukee Bucks* (5)  11.9
17           Anthony Davis      Los Angeles Lakers* (3)  11.9
24       Victor Wembanyama       San Antonio Spurs (13)  11.0
169            Rudy Gobert  Minnesota Timberwolves* (6)  10.9
181     Isaiah Hartenstein   Oklahoma City Thunder* (1)  10.7

                Player                       Team   AST
26          Trae Young         Atlanta Hawks* (8)  11.6
2         Nikola Jokić        Denver Nuggets* (4)  10.2
69   Tyrese Haliburton        Indiana Pacers* (4)   9.2
10     Cade Cunningham       Detroit Pistons* (6)   9.1
38        James Harden  Los Angeles Clippers* (5)   8.7
22        LeBron James    Los Angeles Lakers* (3)   8.2
584      Elfrid Payton  New Orleans Pelicans (14)   8.1
4          Luka Dončić     Dallas Mavericks* (10)   7.8
5          Luka Dončić    Los Angeles Lakers* (3)   7.5
14         LaMelo Ball     Charlotte Hornets (14)   7.4

               Player                      Team    FG%
481         Kai Jones    Dallas Mavericks* (10)  0.836
426      N'Faly Dante      Houston Rockets* (2)  0.769
448       Moses Brown    Dallas Mavericks* (10)  0.724
383      Jaxson Hayes   Los Angeles Lakers* (3)  0.722
135     Jarrett Allen  Cleveland Cavaliers* (1)  0.706
449         Adem Bona   Philadelphia 76ers (13)  0.703
161    Daniel Gafford    Dallas Mavericks* (10)  0.702
294  Dereck Lively II    Dallas Mavericks* (10)  0.702
175       Jalen Duren      Detroit Pistons* (6)  0.692
667      Jericho Sims      Milwaukee Bucks* (5)  0.680

In [20]:
#Exporting League Leaders as a Single CSV

pts_leaders = full_df.nlargest(10, 'PTS')[['Player', 'Team', 'PTS']]
pts_leaders['Category'] = 'Points'

trb_leaders = full_df.nlargest(10, 'TRB')[['Player', 'Team', 'TRB']]
trb_leaders['Category'] = 'Rebounds'

ast_leaders = full_df.nlargest(10, 'AST')[['Player', 'Team', 'AST']]
ast_leaders['Category'] = 'Assists'

fg_leaders = full_df.nlargest(10, 'FG%')[['Player', 'Team', 'FG%']]
fg_leaders['Category'] = 'Field Goal Percentage'

#Normalizing the Stat Column Name since Category will show which Stat is being shown
pts_leaders = pts_leaders.rename(columns={'PTS': 'Stat'})
trb_leaders = trb_leaders.rename(columns={'TRB': 'Stat'})
ast_leaders = ast_leaders.rename(columns={'AST': 'Stat'})
fg_leaders = fg_leaders.rename(columns={'FG%': 'Stat'})


league_leaders = pd.concat([pts_leaders, trb_leaders, ast_leaders, fg_leaders], ignore_index=True)
league_leaders

league_leaders.to_csv('league_leaders.csv', index=False)

,Player,Team,Stat,Category
0,Shai Gilgeous-Alexander,Oklahoma City Thunder* (1),32.700,Points
1,Giannis Antetokounmpo,Milwaukee Bucks* (5),30.400,Points
2,Nikola Jokić,Denver Nuggets* (4),29.600,Points
3,Luka Dončić,Los Angeles Lakers* (3),28.200,Points
4,Luka Dončić,Dallas Mavericks* (10),28.100,Points
5,Anthony Edwards,Minnesota Timberwolves* (6),27.600,Points
6,Jayson Tatum,Boston Celtics* (2),26.800,Points
7,Kevin Durant,Phoenix Suns (11),26.600,Points
8,Tyrese Maxey,Philadelphia 76ers (13),26.300,Points
9,Cade Cunningham,Detroit Pistons* (6),26.100,Points
10,Domantas Sabonis,Sacramento Kings* (9),13.900,Rebounds
11,Karl-Anthony Towns,New York Knicks* (3),12.800,Rebounds
12,Nikola Jokić,Denver Nuggets* (4),12.700,Rebounds
13,Ivica Zubac,Los Angeles Clippers* (5),12.600,Rebounds
14,Walker Kessler,Utah Jazz (15),12.200,Rebounds
15,Giannis Antetokounmpo,Milwaukee Bucks* (5),11.900,Rebounds
16,Anthony Davis,Los Angeles Lakers* (3),11.900,Rebounds
17,Victor Wembanyama,San Antonio Spurs (13),11.000,Rebounds
18,Rudy Gobert,Minnesota Timberwolves* (6),10.900,Rebounds
19,Isaiah Hartenstein,Oklahoma City Thunder* (1),10.700,Rebounds
20,Trae Young,Atlanta Hawks* (8),11.600,Assists
21,Nikola Jokić,Denver Nuggets* (4),10.200,Assists
22,Tyrese Haliburton,Indiana Pacers* (4),9.200,Assists
23,Cade Cunningham,Detroit Pistons* (6),9.100,Assists
24,James Harden,Los Angeles Clippers* (5),8.700,Assists
25,LeBron James,Los Angeles Lakers* (3),8.200,Assists
26,Elfrid Payton,New Orleans Pelicans (14),8.100,Assists
27,Luka Dončić,Dallas Mavericks* (10),7.800,Assists
28,Luka Dončić,Los Angeles Lakers* (3),7.500,Assists
29,LaMelo Ball,Charlotte Hornets (14),7.400,Assists
30,Kai Jones,Dallas Mavericks* (10),0.836,Field Goal Percentage
31,N'Faly Dante,Houston Rockets* (2),0.769,Field Goal Percentage
32,Moses Brown,Dallas Mavericks* (10),0.724,Field Goal Percentage
33,Jaxson Hayes,Los Angeles Lakers* (3),0.722,Field Goal Percentage
34,Jarrett Allen,Cleveland Cavaliers* (1),0.706,Field Goal Percentage
35,Adem Bona,Philadelphia 76ers (13),0.703,Field Goal Percentage
36,Daniel Gafford,Dallas Mavericks* (10),0.702,Field Goal Percentage
37,Dereck Lively II,Dallas Mavericks* (10),0.702,Field Goal Percentage
38,Jalen Duren,Detroit Pistons* (6),0.692,Field Goal Percentage
39,Jericho Sims,Milwaukee Bucks* (5),0.680,Field Goal Percentage

In [21]:
#Top NBA Teams by Points per Game and Points Allowed per Game
full_standings.nlargest(10, 'PS/G')[['Team', 'PS/G']]
full_standings.nsmallest(10, 'PA/G')[['Team', 'PA/G']]

                          Team   PS/G
0     Cleveland Cavaliers* (1)  121.9
22      Memphis Grizzlies* (8)  121.7
18         Denver Nuggets* (4)  120.8
15  Oklahoma City Thunder* (1)  120.5
7           Atlanta Hawks* (8)  118.2
8           Chicago Bulls* (9)  117.8
3          Indiana Pacers* (4)  117.4
1          Boston Celtics* (2)  116.3
2         New York Knicks* (3)  115.8
23       Sacramento Kings* (9)  115.7

                           Team   PA/G
6            Orlando Magic* (7)  105.5
1           Boston Celtics* (2)  107.2
15   Oklahoma City Thunder* (1)  107.6
19    Los Angeles Clippers* (5)  108.2
20  Minnesota Timberwolves* (6)  109.3
16         Houston Rockets* (2)  109.8
9              Miami Heat* (10)  110.0
21   Golden State Warriors* (7)  110.5
2          New York Knicks* (3)  111.7
11           Brooklyn Nets (12)  112.2

In [22]:
#I'm using the same Process as Player League Leaders for Exporting Team League Leaders in a single CSV
PS_leaders = full_standings.nlargest(10, 'PS/G')[['Team', 'PS/G']]
PS_leaders['Category'] = 'Points Scored Per Game'

PA_leaders = full_standings.nsmallest(10, 'PA/G')[['Team', 'PA/G']]
PA_leaders['Category'] = 'Points Allowed Per Game'

PS_leaders = PS_leaders.rename(columns={'PS/G': 'Stat'})
PA_leaders = PA_leaders.rename(columns={'PA/G': 'Stat'})


team_league_leaders = pd.concat([PS_leaders, PA_leaders], ignore_index=True)
team_league_leaders

team_league_leaders.to_csv('team_league_leaders.csv', index=False)

                           Team   Stat                 Category
0      Cleveland Cavaliers* (1)  121.9   Points Scored Per Game
1        Memphis Grizzlies* (8)  121.7   Points Scored Per Game
2           Denver Nuggets* (4)  120.8   Points Scored Per Game
3    Oklahoma City Thunder* (1)  120.5   Points Scored Per Game
4            Atlanta Hawks* (8)  118.2   Points Scored Per Game
5            Chicago Bulls* (9)  117.8   Points Scored Per Game
6           Indiana Pacers* (4)  117.4   Points Scored Per Game
7           Boston Celtics* (2)  116.3   Points Scored Per Game
8          New York Knicks* (3)  115.8   Points Scored Per Game
9         Sacramento Kings* (9)  115.7   Points Scored Per Game
10           Orlando Magic* (7)  105.5  Points Allowed Per Game
11          Boston Celtics* (2)  107.2  Points Allowed Per Game
12   Oklahoma City Thunder* (1)  107.6  Points Allowed Per Game
13    Los Angeles Clippers* (5)  108.2  Points Allowed Per Game
14  Minnesota Timberwolves* (6)  109.3  Points Allowed Per Game
15         Houston Rockets* (2)  109.8  Points Allowed Per Game
16             Miami Heat* (10)  110.0  Points Allowed Per Game
17   Golden State Warriors* (7)  110.5  Points Allowed Per Game
18         New York Knicks* (3)  111.7  Points Allowed Per Game
19           Brooklyn Nets (12)  112.2  Points Allowed Per Game

In [24]:
#Statistics for a Team of your Choice, Will Create a CSV file automatically
team = input("Please enter an NBA team (abbreviation) ")
individual_team_stats = full_df[full_df['abbreviation'] == team]
individual_team_stats.sort_values("PTS", ascending = False)

filename = f"{team}_stats.csv"
individual_team_stats.to_csv(filename, index=False)

Please enter an NBA team (abbreviation) NYK

,Rk,Player,Age,abbreviation,Pos,G,GS,MP,FG,FGA,...,PTS,Awards,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
11,10.0,Jalen Brunson,28.0,NYK,PG,65.0,65.0,35.4,9.0,18.5,...,26.0,NaN,New York Knicks* (3),51.0,31.0,0.622,13.0,115.8,111.7,3.59
23,20.0,Karl-Anthony Towns,29.0,NYK,C,72.0,72.0,35.0,8.9,16.9,...,24.4,NaN,New York Knicks* (3),51.0,31.0,0.622,13.0,115.8,111.7,3.59
79,70.0,OG Anunoby,27.0,NYK,PF,74.0,74.0,36.6,6.6,13.9,...,18.0,NaN,New York Knicks* (3),51.0,31.0,0.622,13.0,115.8,111.7,3.59
80,71.0,Mikal Bridges,28.0,NYK,SF,82.0,82.0,37.0,7.2,14.4,...,17.6,NaN,New York Knicks* (3),51.0,31.0,0.622,13.0,115.8,111.7,3.59
134,117.0,Josh Hart,29.0,NYK,SG,77.0,77.0,37.6,5.2,10.0,...,13.6,NaN,New York Knicks* (3),51.0,31.0,0.622,13.0,115.8,111.7,3.59
242,204.0,Miles McBride,24.0,NYK,PG,64.0,10.0,24.9,3.5,8.5,...,9.5,NaN,New York Knicks* (3),51.0,31.0,0.622,13.0,115.8,111.7,3.59
376,304.0,Cameron Payne,30.0,NYK,PG,72.0,5.0,15.1,2.5,6.2,...,6.9,NaN,New York Knicks* (3),51.0,31.0,0.622,13.0,115.8,111.7,3.59
392,314.0,Precious Achiuwa,25.0,NYK,C,57.0,10.0,20.5,2.9,5.7,...,6.6,NaN,New York Knicks* (3),51.0,31.0,0.622,13.0,115.8,111.7,3.59
454,360.0,Landry Shamet,27.0,NYK,SG,50.0,0.0,15.2,2.1,4.6,...,5.7,NaN,New York Knicks* (3),51.0,31.0,0.622,13.0,115.8,111.7,3.59
478,378.0,Mitchell Robinson,26.0,NYK,C,17.0,3.0,17.1,2.2,3.3,...,5.1,NaN,New York Knicks* (3),51.0,31.0,0.622,13.0,115.8,111.7,3.59
602,464.0,Delon Wright,32.0,NYK,PG,14.0,5.0,16.4,1.6,3.5,...,4.3,NaN,New York Knicks* (3),51.0,31.0,0.622,13.0,115.8,111.7,3.59
610,470.0,P.J. Tucker,39.0,NYK,SF,3.0,1.0,19.3,1.0,2.3,...,3.0,NaN,New York Knicks* (3),51.0,31.0,0.622,13.0,115.8,111.7,3.59
666,510.0,Jericho Sims,26.0,NYK,C,39.0,5.0,10.8,0.7,1.2,...,1.6,NaN,New York Knicks* (3),51.0,31.0,0.622,13.0,115.8,111.7,3.59

In [25]:
#Full Stats table for Teams' Most Popular Starters, and Everyone else
starters = full_df.groupby('abbreviation', group_keys=False).apply(lambda x: x.nlargest(5, 'GS'))
non_starters = full_df.groupby('abbreviation', group_keys=False).apply(lambda x: x[x['GS'].rank(method='first', ascending=False) > 5])
starters.head(20)

/var/folders/25/dl9l232n2qlc1k4jjhh_zxdw0000gn/T/ipykernel_33619/3709240011.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  starters = full_df.groupby('abbreviation', group_keys=False).apply(lambda x: x.nlargest(5, 'GS'))
/var/folders/25/dl9l232n2qlc1k4jjhh_zxdw0000gn/T/ipykernel_33619/3709240011.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  non_starters = full_df.groupby('abbreviation', group_keys=False).apply(lambda x: x[x['GS'].rank(method='first', ascending=False) > 5])

,Rk,Player,Age,abbreviation,Pos,G,GS,MP,FG,FGA,...,PTS,Awards,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
26,23.0,Trae Young,26.0,ATL,PG,76.0,76.0,36.0,7.4,18.1,...,24.2,NaN,Atlanta Hawks* (8),40.0,42.0,0.488,24.0,118.2,119.3,-1.41
125,108.0,Dyson Daniels,21.0,ATL,SG,76.0,76.0,33.8,6.0,12.1,...,14.1,NaN,Atlanta Hawks* (8),40.0,42.0,0.488,24.0,118.2,119.3,-1.41
153,131.0,Zaccharie Risacher,19.0,ATL,SF,75.0,73.0,24.6,4.8,10.4,...,12.6,NaN,Atlanta Hawks* (8),40.0,42.0,0.488,24.0,118.2,119.3,-1.41
276,230.0,Clint Capela,30.0,ATL,C,55.0,41.0,21.4,4.0,7.1,...,8.9,NaN,Atlanta Hawks* (8),40.0,42.0,0.488,24.0,118.2,119.3,-1.41
136,119.0,Onyeka Okongwu,24.0,ATL,C,74.0,40.0,27.9,5.2,9.2,...,13.4,NaN,Atlanta Hawks* (8),40.0,42.0,0.488,24.0,118.2,119.3,-1.41
95,82.0,Derrick White,30.0,BOS,SG,76.0,76.0,33.9,5.6,12.6,...,16.4,NaN,Boston Celtics* (2),61.0,21.0,0.744,3.0,116.3,107.2,8.28
7,6.0,Jayson Tatum,26.0,BOS,PF,72.0,72.0,36.4,9.2,20.3,...,26.8,NaN,Boston Celtics* (2),61.0,21.0,0.744,3.0,116.3,107.2,8.28
39,32.0,Jaylen Brown,28.0,BOS,SF,63.0,63.0,34.3,8.2,17.7,...,22.2,NaN,Boston Celtics* (2),61.0,21.0,0.744,3.0,116.3,107.2,8.28
183,157.0,Jrue Holiday,34.0,BOS,PG,62.0,62.0,30.6,4.1,9.2,...,11.1,NaN,Boston Celtics* (2),61.0,21.0,0.744,3.0,116.3,107.2,8.28
58,51.0,Kristaps Porziņģis,29.0,BOS,C,42.0,42.0,28.8,6.6,13.7,...,19.5,NaN,Boston Celtics* (2),61.0,21.0,0.744,3.0,116.3,107.2,8.28
54,47.0,Coby White,24.0,CHI,SG,74.0,73.0,33.1,6.9,15.1,...,20.4,NaN,Chicago Bulls* (9),39.0,43.0,0.476,25.0,117.8,119.4,-1.83
72,65.0,Nikola Vučević,34.0,CHI,C,73.0,72.0,31.2,7.5,14.2,...,18.5,NaN,Chicago Bulls* (9),39.0,43.0,0.476,25.0,117.8,119.4,-1.83
118,101.0,Josh Giddey,22.0,CHI,PG,70.0,69.0,30.2,5.3,11.4,...,14.6,NaN,Chicago Bulls* (9),39.0,43.0,0.476,25.0,117.8,119.4,-1.83
35,29.0,Zach LaVine,29.0,CHI,SF,42.0,42.0,34.1,8.6,16.9,...,24.0,NaN,Chicago Bulls* (9),39.0,43.0,0.476,25.0,117.8,119.4,-1.83
272,228.0,Patrick Williams,23.0,CHI,PF,63.0,36.0,25.0,3.3,8.2,...,9.0,NaN,Chicago Bulls* (9),39.0,43.0,0.476,25.0,117.8,119.4,-1.83
339,277.0,Josh Green,24.0,CHO,SG,68.0,67.0,27.8,2.6,6.2,...,7.4,NaN,Charlotte Hornets (14),19.0,63.0,0.232,45.0,105.1,114.2,-9.10
55,48.0,Miles Bridges,26.0,CHO,PF,64.0,64.0,31.7,7.3,17.0,...,20.3,NaN,Charlotte Hornets (14),19.0,63.0,0.232,45.0,105.1,114.2,-9.10
14,13.0,LaMelo Ball,23.0,CHO,PG,47.0,47.0,32.0,8.6,21.3,...,25.2,NaN,Charlotte Hornets (14),19.0,63.0,0.232,45.0,105.1,114.2,-9.10
106,93.0,Mark Williams,23.0,CHO,C,44.0,41.0,26.6,6.1,10.2,...,15.3,NaN,Charlotte Hornets (14),19.0,63.0,0.232,45.0,105.1,114.2,-9.10
51,44.0,Brandon Miller,22.0,CHO,SF,27.0,27.0,34.2,7.3,18.2,...,21.0,NaN,Charlotte Hornets (14),19.0,63.0,0.232,45.0,105.1,114.2,-9.10

In [26]:
#Summary Scoring Stats for Starters vs Non Starters Leaguewide
cols = ['PTS','FGA','FG%']
starters[cols].describe()
non_starters[cols].describe()

              PTS         FGA         FG%
count  145.000000  145.000000  145.000000
mean    16.411724   12.568276    0.483179
std      6.198885    4.521564    0.069322
min      3.400000    2.900000    0.372000
25%     11.100000    8.400000    0.439000
50%     16.100000   12.400000    0.469000
75%     21.100000   16.400000    0.509000
max     32.700000   21.800000    0.722000

              PTS         FGA         FG%
count  346.000000  346.000000  346.000000
mean     8.070809    6.522543    0.456850
std      4.358565    3.292409    0.083564
min      1.000000    1.200000    0.125000
25%      5.025000    4.125000    0.413000
50%      7.200000    5.800000    0.448000
75%     10.075000    7.900000    0.492750
max     28.200000   21.200000    0.836000

In [27]:
#Saving Summary Stats as CSVs
starters_SS = starters[cols].describe()
non_starters_SS = non_starters[cols].describe()

starters_SS.to_csv("starters_summary_stats.csv", index=False)
non_starters_SS.to_csv("non_starters_summary_stats.csv", index=False)